# Generated by Django 3.2.14 on 2022-08-29 13:24

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.node')),
                ('twitter_id', models.CharField(default=None, max_length=20, null=True, unique=True, verbose_name='Twitter ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='twitter.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.node',),
        ),
        migrations.CreateModel(
            name='DescriptionChangeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='FollowEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='NameChangeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='TweetEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='UnfollowEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='UsernameChangeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.node')),
                ('twitter_id', models.CharField(max_length=20, unique=True)),
                ('text', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField()),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('quote_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('core.node',),
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('api_version', models.CharField(choices=[('V1', 'Version 1'), ('V2', 'Version 2')], default='V1', max_length=2, verbose_name='API Version')),
                ('api_key', models.CharField(max_length=25, verbose_name='API Key')),
                ('api_key_secret', models.CharField(max_length=50, verbose_name='API Secret Key')),
                ('access_token', models.CharField(max_length=50, verbose_name='API Access Token')),
                ('access_token_secret', models.CharField(max_length=50, verbose_name='API Secret Access Token')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.account')),
            ],
            options={
                'unique_together': {('api_key', 'access_token', 'api_version')},
            },
        ),
    ]
