# Generated by Django 3.2.14 on 2022-08-05 12:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.node')),
                ('twitter_id', models.CharField(default=None, max_length=20, null=True, unique=True, verbose_name='Twitter ID')),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='twitter.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.node',),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.node')),
                ('twitter_id', models.CharField(max_length=20, unique=True)),
                ('text', models.CharField(max_length=600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.node',),
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('api_version', models.CharField(choices=[('V1', 'API Version 1'), ('V2', 'API Version 2')], default='V1', max_length=2, verbose_name='API Version')),
                ('api_key', models.CharField(max_length=25, verbose_name='API Key')),
                ('api_key_secret', models.CharField(max_length=50, verbose_name='API Secret Key')),
                ('access_token', models.CharField(max_length=50, verbose_name='API Access Token')),
                ('access_token_secret', models.CharField(max_length=50, verbose_name='API Secret Access Token')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.account')),
            ],
            options={
                'unique_together': {('api_key', 'access_token', 'api_version')},
            },
        ),
    ]
