# Generated by Django 3.2.14 on 2022-09-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='quote_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='reply_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_count',
        ),
    ]
