# Generated by Django 3.2.14 on 2022-09-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220903_2014'),
        ('twitter', '0002_auto_20220903_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.action')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.action',),
        ),
    ]
