# Generated by Django 3.2.14 on 2022-09-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220903_2023'),
        ('twitter', '0003_likeaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.action')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.action',),
        ),
        migrations.RemoveField(
            model_name='likeaction',
            name='action_ptr',
        ),
        migrations.AddField(
            model_name='likeaction',
            name='twitteraction_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitteraction'),
            preserve_default=False,
        ),
    ]
