# Generated by Django 3.2.14 on 2022-09-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_alter_tweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
