# Generated by Django 3.2.14 on 2022-08-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20220805_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='api_version',
            field=models.CharField(choices=[('V1', 'Version 1'), ('V2', 'Version 2')], default='V1', max_length=2, verbose_name='API Version'),
        ),
    ]
