# Generated by Django 3.2.14 on 2022-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_alter_account_twitter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
