# Generated by Django 3.2.14 on 2022-10-05 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_account_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('status', model_utils.fields.StatusField(choices=[('running', 'running'), ('waiting', 'waiting'), ('stopped', 'stopped')], default='running', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow', models.ManyToManyField(blank=True, to='twitter.Account')),
                ('handle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.handle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
