# Generated by Django 3.2.14 on 2022-09-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220905_1106'),
        ('twitter', '0004_auto_20220903_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.event',),
        ),
        migrations.RemoveField(
            model_name='descriptionchangeevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='followevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='namechangeevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='tweetevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='unfollowevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='usernamechangeevent',
            name='event_ptr',
        ),
        migrations.AddField(
            model_name='descriptionchangeevent',
            name='twitterevent_ptr',
            field=models.OneToOneField(auto_created=True, default=10, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitterevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followevent',
            name='twitterevent_ptr',
            field=models.OneToOneField(auto_created=True, default=20, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitterevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namechangeevent',
            name='twitterevent_ptr',
            field=models.OneToOneField(auto_created=True, default=30, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitterevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetevent',
            name='twitterevent_ptr',
            field=models.OneToOneField(auto_created=True, default=40, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitterevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unfollowevent',
            name='twitterevent_ptr',
            field=models.OneToOneField(auto_created=True, default=50, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitterevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernamechangeevent',
            name='twitterevent_ptr',
            field=models.OneToOneField(auto_created=True, default=60, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitterevent'),
            preserve_default=False,
        ),
    ]
