# Generated by Django 3.2.14 on 2022-09-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20220905_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowAction',
            fields=[
                ('twitteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitteraction')),
            ],
            options={
                'abstract': False,
            },
            bases=('twitter.twitteraction',),
        ),
        migrations.CreateModel(
            name='UnfollowAction',
            fields=[
                ('twitteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitteraction')),
            ],
            options={
                'abstract': False,
            },
            bases=('twitter.twitteraction',),
        ),
    ]
