# Generated by Django 3.2.14 on 2022-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('waiting', 'waiting'), ('stopped', 'stopped')], default='waiting', max_length=10),
        ),
    ]
