# Generated by Django 3.2.14 on 2022-08-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_alter_handle_api_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
    ]
