# Generated by Django 3.2.14 on 2022-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
