# Generated by Django 3.2.14 on 2022-10-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_group'),
        ('twitter', '0006_alter_stream_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='follow',
        ),
        migrations.AddField(
            model_name='stream',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
            preserve_default=False,
        ),
    ]
