# Generated by Django 3.2.14 on 2022-10-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_group_polymorphic_ctype'),
        ('twitter', '0007_auto_20221005_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.group')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.group',),
        ),
    ]
