# Generated by Django 3.2.14 on 2022-08-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(default=None, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='twitter_id',
            field=models.CharField(default=None, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
