# Generated by Django 3.2.14 on 2022-08-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20220802_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='twitter_id',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
