# Generated by Django 3.2.14 on 2022-10-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_group_polymorphic_ctype'),
        ('twitter', '0009_alter_stream_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.group')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.group',),
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='twittergroup_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twittergroup'),
            preserve_default=False,
        ),
    ]
