# Generated by Django 3.2.14 on 2022-08-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='twitter_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
