# Generated by Django 3.2.14 on 2022-10-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('twitter', '0010_auto_20221005_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='stream',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult'),
        ),
    ]
