# Generated by Django 3.2.14 on 2022-10-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_auto_20221005_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='task',
        ),
        migrations.AddField(
            model_name='stream',
            name='task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
