# Generated by Django 3.2.14 on 2022-10-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_auto_20221005_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetweetAction',
            fields=[
                ('twitteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twitter.twitteraction')),
            ],
            options={
                'abstract': False,
            },
            bases=('twitter.twitteraction',),
        ),
    ]
