# Generated by Django 3.2.14 on 2022-08-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0014_auto_20220803_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handle',
            old_name='account',
            new_name='user',
        ),
    ]
