# Generated by Django 3.2.14 on 2022-08-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0015_rename_account_handle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='handle',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='handle',
            unique_together={('api_key', 'access_token')},
        ),
    ]
