# Generated by Django 3.2.14 on 2022-08-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0017_alter_handle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='handle',
            name='api_version',
            field=models.CharField(choices=[('V1', 'API Version 1'), ('V2', 'API Version 2')], default='V1', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='handle',
            unique_together={('api_key', 'access_token', 'api_version')},
        ),
    ]
