# Generated by Django 3.2.14 on 2022-08-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0018_auto_20220803_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handle',
            old_name='api_secret_key',
            new_name='api_key_secret',
        ),
    ]
