# Generated by Django 3.2.14 on 2022-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0019_rename_api_secret_key_handle_api_key_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='twitter_id',
            field=models.CharField(default=None, max_length=20, null=True, unique=True, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='access_token',
            field=models.CharField(max_length=50, verbose_name='API Access Token'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='access_token_secret',
            field=models.CharField(max_length=50, verbose_name='API Secret Access Token'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='api_key',
            field=models.CharField(max_length=25, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='api_key_secret',
            field=models.CharField(max_length=50, verbose_name='API Secret Key'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='api_version',
            field=models.CharField(choices=[('V1', 'API Version 1'), ('V2', 'API Version 2')], default='V1', max_length=2, verbose_name='API Version'),
        ),
    ]
