# Generated by Django 3.2.14 on 2022-08-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0022_auto_20220803_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.account'),
        ),
    ]
