# Generated by Django 3.2.14 on 2022-09-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='actions',
        ),
        migrations.AddField(
            model_name='monitor',
            name='action_temp',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.action'),
            preserve_default=False,
        ),
    ]
