# Generated by Django 3.2.14 on 2022-09-03 20:14

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_auto_20220829_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='action',
        ),
        migrations.AddField(
            model_name='monitor',
            name='action_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'core'), _negated=True), ('model__endswith', 'action')), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='event_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), _negated=True), ('model__endswith', 'event')), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.action_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
