# Generated by Django 3.2.14 on 2022-09-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220921_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='action_temp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.action'),
        ),
    ]
