# Generated by Django 3.2.14 on 2022-09-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_monitor_action_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='action_temp',
        ),
        migrations.AddField(
            model_name='monitor',
            name='actions',
            field=models.ManyToManyField(related_name='monitors', to='core.Action'),
        ),
    ]
