# Generated by Django 3.2.14 on 2022-09-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220903_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='action_type',
        ),
        migrations.AddField(
            model_name='monitor',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.action'),
            preserve_default=False,
        ),
    ]
