# Generated by Django 3.2.14 on 2022-09-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220921_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='actions',
        ),
        migrations.AddField(
            model_name='monitor',
            name='actions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='core.action'),
            preserve_default=False,
        ),
    ]
