# Generated by Django 3.2.14 on 2022-09-21 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220921_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='actions',
        ),
        migrations.AddField(
            model_name='action',
            name='event_monitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.monitor'),
            preserve_default=False,
        ),
    ]
