# Generated by Django 3.2.14 on 2022-09-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_edge_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='actions',
            field=models.ManyToManyField(to='core.Action'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.node'),
        ),
    ]
