# Generated by Django 3.2.14 on 2022-09-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_auto_20220905_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='event_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_monitors', to='core.node'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='event_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_monitors', to='core.node'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='event_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), _negated=True), ('model__endswith', 'event')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
