# Generated by Django 3.2.14 on 2022-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220905_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='action',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='actions',
            field=models.ManyToManyField(related_name='actions', to='core.Action'),
        ),
    ]
