# Generated by Django 3.2.14 on 2022-10-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_group_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created',
        ),
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='group',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='group',
            name='node_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.node'),
            preserve_default=False,
        ),
    ]
