# Generated by Django 3.2.14 on 2022-09-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220905_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='actions',
        ),
    ]
