# Generated by Django 3.2.14 on 2022-10-10 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_action_max_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='max_delay',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
