# Generated by Django 3.2.14 on 2022-09-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_monitor_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.node'),
            preserve_default=False,
        ),
    ]
