# Generated by Django 3.2.14 on 2022-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220905_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='actions',
            field=models.ManyToManyField(to='core.Action'),
        ),
    ]
