# Generated by Django 3.2.14 on 2022-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_action_max_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='max_nodes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='action',
            name='min_nodes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
