# Generated by Django 3.2.14 on 2022-09-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_monitor_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='actions',
        ),
        migrations.AddField(
            model_name='action',
            name='monitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.monitor'),
            preserve_default=False,
        ),
    ]
