# Generated by Django 3.2.14 on 2022-09-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220905_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.monitor'),
        ),
    ]
