# Generated by Django 3.2.14 on 2022-10-12 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221012_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='max_delay',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='action',
            name='min_delay',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
