# Generated by Django 3.2.14 on 2022-10-12 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20221012_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='max_delay',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='action',
            name='min_delay',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
